# Robbyrussell theme
format = """
$character\
$directory\
$git_branch\
$git_status"""

add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[directory]
truncation_length = 1

[git_branch]
format = '[$symbol:\([$branch](bold red)\)](bold blue) '
symbol = 'git'

[git_status]
style = "bold yellow"
